---
title: "Day 2 Afternoon Tasks & Group Activities"
author: "Halina Do-Linh"
date: "8/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(palmerpenguins)
```

### First Order Univariate Derivatives 
$f(x) = x^2$ at x = 3 
```{r}

fx <- expression(x ^ 2)

dx <- D(expr = fx, "x")

dx
```

$P(a) = 2(3a +2)^4 -5$ at a = 1.2
```{r}

pa <- expression(2 * ((3*a + 2)^4) - 5)

dp <- D(expr = pa, "a")

dp

```

$g(t) = (-4t)/(t^2+1)^3)$ at t = 0
```{r}

gt <- expression((-4 * t) / (((t ^ 2) + 1) ^ 3))

dg <- D(expr = gt, "t")

dg
```

### Higher Order Univariate Derivatives 
$G(z) = 4.6 - 1.9z^3$
```{r}

gz <- expression(4.6 - (1.9 * z ^ 3))

dz <- D(expr = gz, "z")

dz

d2g_dz2 <- expression(-5.7 * z ^ 2)

d2g <- D(expr = d2g_dz2, "z")

d2g

# Did not need to reassign the expression! Just use the D() again. So d2g_dz2 <- D(expr = dz, "z")

```


### Partial Order Derivatives
$f(x,y,z) = 2x^2y - 3x + 1 + 4z^4x$
```{r}

f_xyz <- expression((2 * (x ^ 2) * y) - (3 * x) + 1 + (4 * z ^ 4) * x)

df_dx <- D(expr = f_xyz, "x")

df_dy <- D(expr = f_xyz, "y")

df_dz <- D(expr = f_xyz, "z")


```

### Make Some Plots! 
$f(x) = 2.4e^-0.05x^ * sin(x)$ for x values from -0.5 to 0.5
```{r}

eq <- function(x) {
  
  2.4 * exp(-0.05 * x) * sin(x)
  
}

ggplot(data = data.frame(x = c(-0.5, 0.5)), aes(x = x)) + 
         stat_function(fun = eq)

```


### Time for a Penguin Graph
```{r}

ggplot(data = penguins, aes(x = bill_depth_mm, y = bill_length_mm)) +
  geom_point(aes(color = species))


```


## Time for a Penguin-Jitterplot Graph!

```{r}

ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) +
  geom_jitter(aes(color = species)) +
  labs(x = "Species",
       y = "Flipper Length (mm)",
       title = "Flipper Length by Antartica Penguin Species")
  

```

